input("What is your name!!")
print("hleoo")
print ("";jlsadf;"")
input("What is your name!!")
print("hleoo")
print ("";jlsadf;"")
input("What is your name!!")
print("hleoo")
print ("";jlsadf;"")
input("What is your name!!")
print("hleoo")
print ("";jlsadf;"")
